### PR TITLE
[unifi] update unifi to 7.4.162

### PR DESCRIPTION
**Pull request by si458**
**Description of the change**

**Benefits**

**Possible drawbacks**

**Applicable issues**

- fixes #

**Additional information**

**Checklist** 
- [x] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Chart `artifacthub.io/changes` changelog annotation has been updated in `Chart.yaml`. See [Artifact Hub documentation](https://artifacthub.io/docs/topics/annotations/helm/#supported-annotations) for more info.
- [x] Variables have been documented in the `values.yaml` file.

### CODE REVIEW

**Review by funkypenguin — CHANGES_REQUESTED** [review]
I think the way to do this is to add multiple entries, so that there's a history of changes in artifacthub.. so something like this:

```
- kind: changed
  description: did something
- kind: changed
  description: did something else...
```

**Review by funkypenguin — CHANGES_REQUESTED** [review]
Looks good, thank you @si458 , just one minor change on the artifacthub metadata please :)

**Comment by si458** [comment]
> I think the way to do this is to add multiple entries, so that there's a history of changes in artifacthub.. so something like this:
> 
> ```
> - kind: changed
>   description: did something
> - kind: changed
>   description: did something else...
> ```

should be ok 👍 sorry new to the update process!

EDIT: NO I WAS RIGHT THE FIRST TIME AROUND!
https://blog.artifacthub.io/blog/changelogs/
`The changes only need to include those for the current version. Artifact Hub builds the multi-release changelog from changes for each version`

**Comment by si458** [comment]
oh dear the release failed its guthub action! 😱

**Comment by funkypenguin** [comment]
Oof, looks like I need to tidy up these actions! Sorry about that, I'll take a look today...

**Comment by si458** [comment]
> Oof, looks like I need to tidy up these actions! Sorry about that, I'll take a look today...

no rush! im just building my cluster of apps, and alot of your helm charts are perfect! they just need the app versions updating!

EDIT: found these which might help
https://github.com/shaybentk/helm-docs-action
https://github.com/norwoodj/helm-docs

**Pull request merged**
